// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd7i7w9j9mSfliMfQtPNgNuvF8qr0baNY',
    appId: '1:30595934253:web:2882a8d73bc654a99530a4',
    messagingSenderId: '30595934253',
    projectId: 'flash-chat-9875b',
    authDomain: 'flash-chat-9875b.firebaseapp.com',
    storageBucket: 'flash-chat-9875b.appspot.com',
    measurementId: 'G-RCQFRCG5J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKysuqbg3iKIfZHkkKBns7BROrOImKjBU',
    appId: '1:30595934253:android:0e35949d8a0198a29530a4',
    messagingSenderId: '30595934253',
    projectId: 'flash-chat-9875b',
    storageBucket: 'flash-chat-9875b.appspot.com',
  );
}
